# docker compose up --build --no-deps --force-recreate --remove-orphans
services:
  vulnerabilities:
    container_name: vulnerabilities-django
    build:
      context: .
      dockerfile: ./vulnerabilities.Dockerfile
    networks:
      - local_network
    volumes:
      - .:/app
      - .vulnerabilities:/.vulnerabilities
      - /app/.alertmanager/_data
      - /app/.alloy/_data
      - /app/.grafana/_data
      - /app/.jenkins-data
      - /app/.loki/_data
      - /app/.prometheus/_data
      - /app/.tempo/_data
    restart: unless-stopped

  jenkins:
    container_name: jenkins-django
    build:
      context: .
      dockerfile: ./jenkins.Dockerfile
    privileged: true
    user: root
    networks:
      - local_network
    ports:
      - "8080:8080" # Access UI at http://localhost:8080
      - "50000:50000"
    environment:
      ENV: local
      JAVA_OPTS: -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    volumes:
      - .:/app
      - .jenkins-data:/var/jenkins_home
      - /app/.alertmanager/_data
      - /app/.alloy/_data
      - /app/.grafana/_data
      - /app/.jenkins-data
      - /app/.loki/_data
      - /app/.prometheus/_data
      - /app/.tempo/_data
      - /app/.vulnerabilities
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    restart: unless-stopped

  init:
    container_name: tempo-init-django
    image: busybox:latest
    user: root
    networks:
      - local_network
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - .tempo/_data:/var/tempo

  tempo:
    image: grafana/tempo:2.10.5
    container_name: tempo-django
    command:
      - -target=all
      - -config.file=/etc/tempo.yaml
    volumes:
      - .tempo/config/tempo.yaml:/etc/tempo.yaml
      - .tempo/_data:/var/tempo
    networks:
      - local_network
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "2345:2345" # delve debug server
    depends_on:
      - init

  vulture:
    image: grafana/tempo-vulture:latest
    restart: always
    networks:
      - local_network
    command:
      [
        "-prometheus-listen-address=:8080",
        "-tempo-query-url=http://tempo:3200",
        "-tempo-push-url=http://tempo:4317",
      ]
    depends_on:
      - tempo

  loki:
    image: grafana/loki:3.4.2
    ports:
      - "3100:3100"
    networks:
      - local_network
    volumes:
      - .loki/config/loki-config.yaml:/etc/loki/local-config.yaml
      - .loki/_data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml

  # Generate fake traces...
  # And put them in a Grafana Alloy pipeline...
  # k6-tracing:
  #   image: ghcr.io/grafana/xk6-client-tracing:v0.0.9
  #   environment:
  #     - ENDPOINT=alloy:4320
  #     # - ENDPOINT=alloy:4317
  #     # - ENDPOINT=tempo:4317
  #   networks:
  #     - local_network
  #   restart: always
  #   depends_on:
  #     - tempo
  #     - alloy

  alloy:
    image: grafana/alloy:v1.12.1@sha256:c311595156fca7b1131683d383dae1acfd29e8879d347161d2a6f714ebac0c0b
    container_name: alloy-django
    volumes:
      - .alloy/config/config.alloy:/etc/alloy/config.alloy
      - .alloy/_data:/var/lib/alloy/data
      - ./logging:/django/logging
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    networks:
      - local_network
    environment:
      - ALLOY_OTLP_UPSTREAM=tempo:4317
      - ALLOY_OTLP_LOGS_UPSTREAM="http://loki:3100/otlp"
    ports:
      - "12345:12345"
      - "4319:4317"
      - "4320:4320"
      - "4321:4321"
    depends_on:
      - tempo
      - loki

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-django
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/.prometheus/_data'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=exemplar-storage'
      - '--enable-feature=native-histograms'
    networks:
      - local_network
    ports:
      - "9090:9090" # Access UI at http://localhost:9090
    volumes:
      - .prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml # Mount config file
      - .prometheus/rules/prometheus.rules:/etc/prometheus/prometheus.rules # Mount alert file
      - .prometheus/_data:/.prometheus/_data
    restart: unless-stopped

  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter-django
  #   networks:
  #     - local_network
  #   ports:
  #     - "9100:9100" # Exposes hardware/OS metrics
  #   restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager-django
    ports:
      - "9093:9093"
    networks:
      - local_network
    volumes:
      - .alertmanager/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - .alertmanager/_data:/.alertmanager/_data
    environment:
      - ALERT_MANAGER_SLACK_API_URL=${ALERT_MANAGER_SLACK_API_URL}
      - ALERT_MANAGER_SLACK_API_CHANNEL=${ALERT_MANAGER_SLACK_API_CHANNEL}
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/.alertmanager/_data"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-django
    networks:
      - local_network
    ports:
      - "3000:3000" # Access UI at http://localhost:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default login: admin / admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - .grafana/_data:/var/lib/grafana
      - .grafana/dashboards:/etc/grafana/provisioning/dashboards
      - .grafana/datasources:/etc/grafana/provisioning/datasources
      - .grafana/alerting:/etc/grafana/provisioning/alerting
    restart: unless-stopped

  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   container_name: cadvisor
  #   networks:
  #     - local_network
  #   ports:
  #     - 8090:8080 # Access UI at http://localhost:8090/docker/backend-login-django
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   # cgroup: host
  #   restart: unless-stopped
  #   depends_on:
  #     backend-login-django:
  #       condition: service_started

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    networks:
      - local_network
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-container
    networks:
      - local_network
    ports:
      - 5672:5672  # AMQP port
      - 15672:15672 # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --bind 0.0.0.0 --appendonly yes
    volumes:
      - .redis/_data:/data
    networks:
      - local_network
    ports:
      # - 127.0.0.1:6379:6379
      - 0.0.0.0:6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka:
    image: apache/kafka:4.3.0
    container_name: kafka
    networks:
      - local_network
    ports:
      - 9092:9092

  clamav:
    image: clamav/clamav:stable-debian
    container_name: clamav_scanner
    # command: clamscan --log=/report/clamav.log --move=/quarantine -r -v /app/media
    networks:
      - local_network
    restart: unless-stopped
    ports:
      - "3310:3310"
    volumes:
      - .clamav/_data:/var/lib/clamav
      - .clamav/quarantine:/quarantine
      - .clamav/report:/report
      - ./media:/app/media
    environment:
      - CLAMAV_NO_DB_ONLY=false

  backend-login-django:
    container_name: backend-login-django
    networks:
      - local_network
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    volumes:
      - .:/app
      - ./media:/app/media
      - ./logging:/app/logging
      - /app/.alertmanager/_data
      - /app/.alloy/_data
      - /app/.grafana/_data
      - /app/.jenkins-data
      - /app/.loki/_data
      - /app/.prometheus/_data
      - /app/.tempo/_data
      - /app/.vulnerabilities
    environment:
      ENV: ${ENVIRONMENT}
      SECRET_KEY: ${SECRET_KEY}
      CRYPTOGRAPHY_KEY: ${CRYPTOGRAPHY_KEY}
      DJANGO_LOG_LEVEL: ${DJANGO_LOG_LEVEL}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      REDIS_HOST: host.docker.internal
      RABBIT_MQ_HOST: host.docker.internal
      SENTRY_DNS_DJANGO: ${SENTRY_DNS_DJANGO}
    ports:
      - 8000:8000
    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_started
      prometheus:
        condition: service_started

  nuclei:
    image: projectdiscovery/nuclei:latest
    container_name: nuclei-dast-django
    entrypoint: 
      - /bin/sh
      - -c
      - |
        rm -rf /.vulnerabilities/* \
        && nuclei -verbose \
          -list /app/.dast/nuclei/config/dast.urls.txt \
          -output /.vulnerabilities/nuclei.batteringram.log \
          -trace-log /.vulnerabilities/nuclei.batteringram.trace.log \
          -error-log /.vulnerabilities/nuclei.batteringram.error.log \
          -store-resp-dir /.vulnerabilities/nuclei.batteringram.report \
          -stats \
          -timestamp \
          -matcher-status \
          -debug \
          -debug-req \
          -debug-resp \
          -attack-type batteringram \
        && nuclei -verbose \
          -list /app/dast.urls.txt \
          -output /.vulnerabilities/nuclei.pitchfork.log \
          -trace-log /.vulnerabilities/nuclei.pitchfork.trace.log \
          -error-log /.vulnerabilities/nuclei.pitchfork.error.log \
          -store-resp-dir /.vulnerabilities/nuclei.pitchfork.report \
          -stats \
          -timestamp \
          -matcher-status \
          -debug \
          -debug-req \
          -debug-resp \
          -attack-type pitchfork \
        && nuclei -verbose \
          -list /app/dast.urls.txt \
          -output /.vulnerabilities/nuclei.clusterbomb.log \
          -trace-log /.vulnerabilities/nuclei.clusterbomb.trace.log \
          -error-log /.vulnerabilities/nuclei.clusterbomb.error.log \
          -store-resp-dir /.vulnerabilities/nuclei.clusterbomb.report \
          -stats \
          -timestamp \
          -matcher-status \
          -debug \
          -debug-req \
          -debug-resp \
          -attack-type clusterbomb
    volumes:
      - .:/app
      - .vulnerabilities:/.vulnerabilities
      - /app/.alertmanager/_data
      - /app/.alloy/_data
      - /app/.grafana/_data
      - /app/.jenkins-data
      - /app/.loki/_data
      - /app/.prometheus/_data
      - /app/.tempo/_data
    depends_on:
      backend-login-django:
        condition: service_started

networks:
  local_network:
    driver: bridge
